### ISSUE TITLE
gcc 10: "multiple definition" error

### ISSUE THREAD

**Issue by Enchufa2** [PolMine/RcppCWB#12]
The package fails to build with gcc 10. Here's the log: https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-32-x86_64/01305441-R-CRAN-RcppCWB/builder-live.log.gz

**Comment by ablaette** [comment]
My apologies that you issue did not get a response for such a long time. I just ran tests with Fedora/gcc 10 yesterday. Indeed, there was an error, but it emerged because I ran dockerized tests on a M1 Mac mini and a required -fPIC flag was not set. That's fixed (RcppCWB dev branch).

Unfortunately I cannot access your log. Please let me know whether the error still occurs. Of course this needs to be fixed.

**Comment by Enchufa2** [comment]
As of gcc10, global variables must be declared as extern. If you fixed that at some point, then you can close this issue.

**Comment by ablaette** [comment]
Indeed, I prepended extern declarations to global variables when preparing v3.0.0 (CRAN release in July 2020), so that the -fcommon flag can be ommited. Many thanks for the explanation!
